### PR TITLE
Add Ruby 2.x for testing

### PR DESCRIPTION
**Pull request by brendon**
I was hoping we could get this testing against newer Ruby versions if possible?

### CODE REVIEW

**Comment by qoobaa** [comment]
Thanks.

**Comment by brendon** [comment]
Now the question is, is travis actually running on this project? Can you integrate it with the github repo? :)

**Comment by qoobaa** [comment]
https://travis-ci.org/qoobaa/vcard - here you go

**Comment by brendon** [comment]
Thanks for that. Will future PR's trigger a travis run?

Also to fix the current bundler error add this to `travis.yml`:

```
before_install:
  - gem install bundler
```

And probably remove 1.8.7?

**Comment by qoobaa** [comment]
It should.

Could you create a PR for that? I'm busy with some other things atm.

**Comment by brendon** [comment]
Will do.

**Comment by qoobaa** [comment]
Thanks!

**Comment by brendon** [comment]
#24

**Pull request merged**
